# Generated by Django 6.0 on 2026-02-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoreal',
            name='grasas_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productoreal',
            name='hidratos_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productoreal',
            name='kcal_100g',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productoreal',
            name='prot_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='costeporsupermercado',
            name='es_posible',
            field=models.BooleanField(default=True),
        ),
    ]
